// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogBean.proto

package com.wolf.javabean;

public final class LogBean {
  private LogBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogDatasOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wolf.javabean.LogDatas)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.wolf.javabean.Logs logs = 1;</code>
     */
    boolean hasLogs();
    /**
     * <code>optional .com.wolf.javabean.Logs logs = 1;</code>
     */
    com.wolf.javabean.LogBean.Logs getLogs();
    /**
     * <code>optional .com.wolf.javabean.Logs logs = 1;</code>
     */
    com.wolf.javabean.LogBean.LogsOrBuilder getLogsOrBuilder();
  }
  /**
   * Protobuf type {@code com.wolf.javabean.LogDatas}
   */
  public  static final class LogDatas extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.wolf.javabean.LogDatas)
      LogDatasOrBuilder {
    // Use LogDatas.newBuilder() to construct.
    private LogDatas(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogDatas() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LogDatas(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.wolf.javabean.LogBean.Logs.Builder subBuilder = null;
              if (logs_ != null) {
                subBuilder = logs_.toBuilder();
              }
              logs_ = input.readMessage(com.wolf.javabean.LogBean.Logs.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(logs_);
                logs_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wolf.javabean.LogBean.internal_static_com_wolf_javabean_LogDatas_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wolf.javabean.LogBean.internal_static_com_wolf_javabean_LogDatas_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wolf.javabean.LogBean.LogDatas.class, com.wolf.javabean.LogBean.LogDatas.Builder.class);
    }

    public static final int LOGS_FIELD_NUMBER = 1;
    private com.wolf.javabean.LogBean.Logs logs_;
    /**
     * <code>optional .com.wolf.javabean.Logs logs = 1;</code>
     */
    public boolean hasLogs() {
      return logs_ != null;
    }
    /**
     * <code>optional .com.wolf.javabean.Logs logs = 1;</code>
     */
    public com.wolf.javabean.LogBean.Logs getLogs() {
      return logs_ == null ? com.wolf.javabean.LogBean.Logs.getDefaultInstance() : logs_;
    }
    /**
     * <code>optional .com.wolf.javabean.Logs logs = 1;</code>
     */
    public com.wolf.javabean.LogBean.LogsOrBuilder getLogsOrBuilder() {
      return getLogs();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (logs_ != null) {
        output.writeMessage(1, getLogs());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (logs_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLogs());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wolf.javabean.LogBean.LogDatas)) {
        return super.equals(obj);
      }
      com.wolf.javabean.LogBean.LogDatas other = (com.wolf.javabean.LogBean.LogDatas) obj;

      boolean result = true;
      result = result && (hasLogs() == other.hasLogs());
      if (hasLogs()) {
        result = result && getLogs()
            .equals(other.getLogs());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasLogs()) {
        hash = (37 * hash) + LOGS_FIELD_NUMBER;
        hash = (53 * hash) + getLogs().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wolf.javabean.LogBean.LogDatas parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.LogBean.LogDatas parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.LogBean.LogDatas parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.LogBean.LogDatas parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.LogBean.LogDatas parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.LogBean.LogDatas parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.LogBean.LogDatas parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.LogBean.LogDatas parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.LogBean.LogDatas parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.LogBean.LogDatas parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wolf.javabean.LogBean.LogDatas prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wolf.javabean.LogDatas}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wolf.javabean.LogDatas)
        com.wolf.javabean.LogBean.LogDatasOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wolf.javabean.LogBean.internal_static_com_wolf_javabean_LogDatas_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wolf.javabean.LogBean.internal_static_com_wolf_javabean_LogDatas_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wolf.javabean.LogBean.LogDatas.class, com.wolf.javabean.LogBean.LogDatas.Builder.class);
      }

      // Construct using com.wolf.javabean.LogBean.LogDatas.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (logsBuilder_ == null) {
          logs_ = null;
        } else {
          logs_ = null;
          logsBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wolf.javabean.LogBean.internal_static_com_wolf_javabean_LogDatas_descriptor;
      }

      public com.wolf.javabean.LogBean.LogDatas getDefaultInstanceForType() {
        return com.wolf.javabean.LogBean.LogDatas.getDefaultInstance();
      }

      public com.wolf.javabean.LogBean.LogDatas build() {
        com.wolf.javabean.LogBean.LogDatas result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wolf.javabean.LogBean.LogDatas buildPartial() {
        com.wolf.javabean.LogBean.LogDatas result = new com.wolf.javabean.LogBean.LogDatas(this);
        if (logsBuilder_ == null) {
          result.logs_ = logs_;
        } else {
          result.logs_ = logsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wolf.javabean.LogBean.LogDatas) {
          return mergeFrom((com.wolf.javabean.LogBean.LogDatas)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wolf.javabean.LogBean.LogDatas other) {
        if (other == com.wolf.javabean.LogBean.LogDatas.getDefaultInstance()) return this;
        if (other.hasLogs()) {
          mergeLogs(other.getLogs());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wolf.javabean.LogBean.LogDatas parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wolf.javabean.LogBean.LogDatas) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.wolf.javabean.LogBean.Logs logs_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolf.javabean.LogBean.Logs, com.wolf.javabean.LogBean.Logs.Builder, com.wolf.javabean.LogBean.LogsOrBuilder> logsBuilder_;
      /**
       * <code>optional .com.wolf.javabean.Logs logs = 1;</code>
       */
      public boolean hasLogs() {
        return logsBuilder_ != null || logs_ != null;
      }
      /**
       * <code>optional .com.wolf.javabean.Logs logs = 1;</code>
       */
      public com.wolf.javabean.LogBean.Logs getLogs() {
        if (logsBuilder_ == null) {
          return logs_ == null ? com.wolf.javabean.LogBean.Logs.getDefaultInstance() : logs_;
        } else {
          return logsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.wolf.javabean.Logs logs = 1;</code>
       */
      public Builder setLogs(com.wolf.javabean.LogBean.Logs value) {
        if (logsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          logs_ = value;
          onChanged();
        } else {
          logsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Logs logs = 1;</code>
       */
      public Builder setLogs(
          com.wolf.javabean.LogBean.Logs.Builder builderForValue) {
        if (logsBuilder_ == null) {
          logs_ = builderForValue.build();
          onChanged();
        } else {
          logsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Logs logs = 1;</code>
       */
      public Builder mergeLogs(com.wolf.javabean.LogBean.Logs value) {
        if (logsBuilder_ == null) {
          if (logs_ != null) {
            logs_ =
              com.wolf.javabean.LogBean.Logs.newBuilder(logs_).mergeFrom(value).buildPartial();
          } else {
            logs_ = value;
          }
          onChanged();
        } else {
          logsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Logs logs = 1;</code>
       */
      public Builder clearLogs() {
        if (logsBuilder_ == null) {
          logs_ = null;
          onChanged();
        } else {
          logs_ = null;
          logsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Logs logs = 1;</code>
       */
      public com.wolf.javabean.LogBean.Logs.Builder getLogsBuilder() {
        
        onChanged();
        return getLogsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.wolf.javabean.Logs logs = 1;</code>
       */
      public com.wolf.javabean.LogBean.LogsOrBuilder getLogsOrBuilder() {
        if (logsBuilder_ != null) {
          return logsBuilder_.getMessageOrBuilder();
        } else {
          return logs_ == null ?
              com.wolf.javabean.LogBean.Logs.getDefaultInstance() : logs_;
        }
      }
      /**
       * <code>optional .com.wolf.javabean.Logs logs = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolf.javabean.LogBean.Logs, com.wolf.javabean.LogBean.Logs.Builder, com.wolf.javabean.LogBean.LogsOrBuilder> 
          getLogsFieldBuilder() {
        if (logsBuilder_ == null) {
          logsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wolf.javabean.LogBean.Logs, com.wolf.javabean.LogBean.Logs.Builder, com.wolf.javabean.LogBean.LogsOrBuilder>(
                  getLogs(),
                  getParentForChildren(),
                  isClean());
          logs_ = null;
        }
        return logsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.wolf.javabean.LogDatas)
    }

    // @@protoc_insertion_point(class_scope:com.wolf.javabean.LogDatas)
    private static final com.wolf.javabean.LogBean.LogDatas DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wolf.javabean.LogBean.LogDatas();
    }

    public static com.wolf.javabean.LogBean.LogDatas getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogDatas>
        PARSER = new com.google.protobuf.AbstractParser<LogDatas>() {
      public LogDatas parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LogDatas(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogDatas> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogDatas> getParserForType() {
      return PARSER;
    }

    public com.wolf.javabean.LogBean.LogDatas getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LogsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wolf.javabean.Logs)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *主ID
     * </pre>
     *
     * <code>optional string mainId = 1;</code>
     */
    java.lang.String getMainId();
    /**
     * <pre>
     *主ID
     * </pre>
     *
     * <code>optional string mainId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMainIdBytes();

    /**
     * <pre>
     *调用ID
     * </pre>
     *
     * <code>optional string parentId = 2;</code>
     */
    java.lang.String getParentId();
    /**
     * <pre>
     *调用ID
     * </pre>
     *
     * <code>optional string parentId = 2;</code>
     */
    com.google.protobuf.ByteString
        getParentIdBytes();

    /**
     * <pre>
     *当前ID
     * </pre>
     *
     * <code>optional string id = 3;</code>
     */
    java.lang.String getId();
    /**
     * <pre>
     *当前ID
     * </pre>
     *
     * <code>optional string id = 3;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     *时间
     * </pre>
     *
     * <code>optional string time = 4;</code>
     */
    java.lang.String getTime();
    /**
     * <pre>
     *时间
     * </pre>
     *
     * <code>optional string time = 4;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <pre>
     *消息
     * </pre>
     *
     * <code>optional string message = 5;</code>
     */
    java.lang.String getMessage();
    /**
     * <pre>
     *消息
     * </pre>
     *
     * <code>optional string message = 5;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     *路径
     * </pre>
     *
     * <code>optional string path = 6;</code>
     */
    java.lang.String getPath();
    /**
     * <pre>
     *路径
     * </pre>
     *
     * <code>optional string path = 6;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes();

    /**
     * <pre>
     *服务名
     * </pre>
     *
     * <code>optional string serverName = 7;</code>
     */
    java.lang.String getServerName();
    /**
     * <pre>
     *服务名
     * </pre>
     *
     * <code>optional string serverName = 7;</code>
     */
    com.google.protobuf.ByteString
        getServerNameBytes();

    /**
     * <pre>
     *ip地址
     * </pre>
     *
     * <code>optional string ip = 8;</code>
     */
    java.lang.String getIp();
    /**
     * <pre>
     *ip地址
     * </pre>
     *
     * <code>optional string ip = 8;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <pre>
     *类型，1为正常，0为异常
     * </pre>
     *
     * <code>optional string type = 9;</code>
     */
    java.lang.String getType();
    /**
     * <pre>
     *类型，1为正常，0为异常
     * </pre>
     *
     * <code>optional string type = 9;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code com.wolf.javabean.Logs}
   */
  public  static final class Logs extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.wolf.javabean.Logs)
      LogsOrBuilder {
    // Use Logs.newBuilder() to construct.
    private Logs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Logs() {
      mainId_ = "";
      parentId_ = "";
      id_ = "";
      time_ = "";
      message_ = "";
      path_ = "";
      serverName_ = "";
      ip_ = "";
      type_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Logs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              mainId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              parentId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              time_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              path_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              serverName_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wolf.javabean.LogBean.internal_static_com_wolf_javabean_Logs_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wolf.javabean.LogBean.internal_static_com_wolf_javabean_Logs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wolf.javabean.LogBean.Logs.class, com.wolf.javabean.LogBean.Logs.Builder.class);
    }

    public static final int MAINID_FIELD_NUMBER = 1;
    private volatile java.lang.Object mainId_;
    /**
     * <pre>
     *主ID
     * </pre>
     *
     * <code>optional string mainId = 1;</code>
     */
    public java.lang.String getMainId() {
      java.lang.Object ref = mainId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mainId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *主ID
     * </pre>
     *
     * <code>optional string mainId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMainIdBytes() {
      java.lang.Object ref = mainId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mainId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARENTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object parentId_;
    /**
     * <pre>
     *调用ID
     * </pre>
     *
     * <code>optional string parentId = 2;</code>
     */
    public java.lang.String getParentId() {
      java.lang.Object ref = parentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *调用ID
     * </pre>
     *
     * <code>optional string parentId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getParentIdBytes() {
      java.lang.Object ref = parentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     *当前ID
     * </pre>
     *
     * <code>optional string id = 3;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *当前ID
     * </pre>
     *
     * <code>optional string id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 4;
    private volatile java.lang.Object time_;
    /**
     * <pre>
     *时间
     * </pre>
     *
     * <code>optional string time = 4;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *时间
     * </pre>
     *
     * <code>optional string time = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 5;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     *消息
     * </pre>
     *
     * <code>optional string message = 5;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息
     * </pre>
     *
     * <code>optional string message = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATH_FIELD_NUMBER = 6;
    private volatile java.lang.Object path_;
    /**
     * <pre>
     *路径
     * </pre>
     *
     * <code>optional string path = 6;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *路径
     * </pre>
     *
     * <code>optional string path = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERNAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object serverName_;
    /**
     * <pre>
     *服务名
     * </pre>
     *
     * <code>optional string serverName = 7;</code>
     */
    public java.lang.String getServerName() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *服务名
     * </pre>
     *
     * <code>optional string serverName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 8;
    private volatile java.lang.Object ip_;
    /**
     * <pre>
     *ip地址
     * </pre>
     *
     * <code>optional string ip = 8;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *ip地址
     * </pre>
     *
     * <code>optional string ip = 8;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 9;
    private volatile java.lang.Object type_;
    /**
     * <pre>
     *类型，1为正常，0为异常
     * </pre>
     *
     * <code>optional string type = 9;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *类型，1为正常，0为异常
     * </pre>
     *
     * <code>optional string type = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMainIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mainId_);
      }
      if (!getParentIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, parentId_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, id_);
      }
      if (!getTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, time_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, message_);
      }
      if (!getPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, path_);
      }
      if (!getServerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, serverName_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, ip_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMainIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mainId_);
      }
      if (!getParentIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, parentId_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, id_);
      }
      if (!getTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, time_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, message_);
      }
      if (!getPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, path_);
      }
      if (!getServerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, serverName_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, ip_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wolf.javabean.LogBean.Logs)) {
        return super.equals(obj);
      }
      com.wolf.javabean.LogBean.Logs other = (com.wolf.javabean.LogBean.Logs) obj;

      boolean result = true;
      result = result && getMainId()
          .equals(other.getMainId());
      result = result && getParentId()
          .equals(other.getParentId());
      result = result && getId()
          .equals(other.getId());
      result = result && getTime()
          .equals(other.getTime());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && getPath()
          .equals(other.getPath());
      result = result && getServerName()
          .equals(other.getServerName());
      result = result && getIp()
          .equals(other.getIp());
      result = result && getType()
          .equals(other.getType());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + MAINID_FIELD_NUMBER;
      hash = (53 * hash) + getMainId().hashCode();
      hash = (37 * hash) + PARENTID_FIELD_NUMBER;
      hash = (53 * hash) + getParentId().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
      hash = (37 * hash) + SERVERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getServerName().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wolf.javabean.LogBean.Logs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.LogBean.Logs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.LogBean.Logs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.LogBean.Logs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.LogBean.Logs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.LogBean.Logs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.LogBean.Logs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.LogBean.Logs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.LogBean.Logs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.LogBean.Logs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wolf.javabean.LogBean.Logs prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wolf.javabean.Logs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wolf.javabean.Logs)
        com.wolf.javabean.LogBean.LogsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wolf.javabean.LogBean.internal_static_com_wolf_javabean_Logs_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wolf.javabean.LogBean.internal_static_com_wolf_javabean_Logs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wolf.javabean.LogBean.Logs.class, com.wolf.javabean.LogBean.Logs.Builder.class);
      }

      // Construct using com.wolf.javabean.LogBean.Logs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        mainId_ = "";

        parentId_ = "";

        id_ = "";

        time_ = "";

        message_ = "";

        path_ = "";

        serverName_ = "";

        ip_ = "";

        type_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wolf.javabean.LogBean.internal_static_com_wolf_javabean_Logs_descriptor;
      }

      public com.wolf.javabean.LogBean.Logs getDefaultInstanceForType() {
        return com.wolf.javabean.LogBean.Logs.getDefaultInstance();
      }

      public com.wolf.javabean.LogBean.Logs build() {
        com.wolf.javabean.LogBean.Logs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wolf.javabean.LogBean.Logs buildPartial() {
        com.wolf.javabean.LogBean.Logs result = new com.wolf.javabean.LogBean.Logs(this);
        result.mainId_ = mainId_;
        result.parentId_ = parentId_;
        result.id_ = id_;
        result.time_ = time_;
        result.message_ = message_;
        result.path_ = path_;
        result.serverName_ = serverName_;
        result.ip_ = ip_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wolf.javabean.LogBean.Logs) {
          return mergeFrom((com.wolf.javabean.LogBean.Logs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wolf.javabean.LogBean.Logs other) {
        if (other == com.wolf.javabean.LogBean.Logs.getDefaultInstance()) return this;
        if (!other.getMainId().isEmpty()) {
          mainId_ = other.mainId_;
          onChanged();
        }
        if (!other.getParentId().isEmpty()) {
          parentId_ = other.parentId_;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.getPath().isEmpty()) {
          path_ = other.path_;
          onChanged();
        }
        if (!other.getServerName().isEmpty()) {
          serverName_ = other.serverName_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wolf.javabean.LogBean.Logs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wolf.javabean.LogBean.Logs) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object mainId_ = "";
      /**
       * <pre>
       *主ID
       * </pre>
       *
       * <code>optional string mainId = 1;</code>
       */
      public java.lang.String getMainId() {
        java.lang.Object ref = mainId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mainId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *主ID
       * </pre>
       *
       * <code>optional string mainId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMainIdBytes() {
        java.lang.Object ref = mainId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mainId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *主ID
       * </pre>
       *
       * <code>optional string mainId = 1;</code>
       */
      public Builder setMainId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mainId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主ID
       * </pre>
       *
       * <code>optional string mainId = 1;</code>
       */
      public Builder clearMainId() {
        
        mainId_ = getDefaultInstance().getMainId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主ID
       * </pre>
       *
       * <code>optional string mainId = 1;</code>
       */
      public Builder setMainIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mainId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object parentId_ = "";
      /**
       * <pre>
       *调用ID
       * </pre>
       *
       * <code>optional string parentId = 2;</code>
       */
      public java.lang.String getParentId() {
        java.lang.Object ref = parentId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          parentId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *调用ID
       * </pre>
       *
       * <code>optional string parentId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getParentIdBytes() {
        java.lang.Object ref = parentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *调用ID
       * </pre>
       *
       * <code>optional string parentId = 2;</code>
       */
      public Builder setParentId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        parentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *调用ID
       * </pre>
       *
       * <code>optional string parentId = 2;</code>
       */
      public Builder clearParentId() {
        
        parentId_ = getDefaultInstance().getParentId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *调用ID
       * </pre>
       *
       * <code>optional string parentId = 2;</code>
       */
      public Builder setParentIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        parentId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <pre>
       *当前ID
       * </pre>
       *
       * <code>optional string id = 3;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *当前ID
       * </pre>
       *
       * <code>optional string id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *当前ID
       * </pre>
       *
       * <code>optional string id = 3;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前ID
       * </pre>
       *
       * <code>optional string id = 3;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前ID
       * </pre>
       *
       * <code>optional string id = 3;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <pre>
       *时间
       * </pre>
       *
       * <code>optional string time = 4;</code>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *时间
       * </pre>
       *
       * <code>optional string time = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *时间
       * </pre>
       *
       * <code>optional string time = 4;</code>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间
       * </pre>
       *
       * <code>optional string time = 4;</code>
       */
      public Builder clearTime() {
        
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间
       * </pre>
       *
       * <code>optional string time = 4;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        time_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       *消息
       * </pre>
       *
       * <code>optional string message = 5;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息
       * </pre>
       *
       * <code>optional string message = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息
       * </pre>
       *
       * <code>optional string message = 5;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息
       * </pre>
       *
       * <code>optional string message = 5;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息
       * </pre>
       *
       * <code>optional string message = 5;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <pre>
       *路径
       * </pre>
       *
       * <code>optional string path = 6;</code>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *路径
       * </pre>
       *
       * <code>optional string path = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *路径
       * </pre>
       *
       * <code>optional string path = 6;</code>
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *路径
       * </pre>
       *
       * <code>optional string path = 6;</code>
       */
      public Builder clearPath() {
        
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *路径
       * </pre>
       *
       * <code>optional string path = 6;</code>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        path_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serverName_ = "";
      /**
       * <pre>
       *服务名
       * </pre>
       *
       * <code>optional string serverName = 7;</code>
       */
      public java.lang.String getServerName() {
        java.lang.Object ref = serverName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *服务名
       * </pre>
       *
       * <code>optional string serverName = 7;</code>
       */
      public com.google.protobuf.ByteString
          getServerNameBytes() {
        java.lang.Object ref = serverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *服务名
       * </pre>
       *
       * <code>optional string serverName = 7;</code>
       */
      public Builder setServerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务名
       * </pre>
       *
       * <code>optional string serverName = 7;</code>
       */
      public Builder clearServerName() {
        
        serverName_ = getDefaultInstance().getServerName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务名
       * </pre>
       *
       * <code>optional string serverName = 7;</code>
       */
      public Builder setServerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <pre>
       *ip地址
       * </pre>
       *
       * <code>optional string ip = 8;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *ip地址
       * </pre>
       *
       * <code>optional string ip = 8;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *ip地址
       * </pre>
       *
       * <code>optional string ip = 8;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ip地址
       * </pre>
       *
       * <code>optional string ip = 8;</code>
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ip地址
       * </pre>
       *
       * <code>optional string ip = 8;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <pre>
       *类型，1为正常，0为异常
       * </pre>
       *
       * <code>optional string type = 9;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *类型，1为正常，0为异常
       * </pre>
       *
       * <code>optional string type = 9;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *类型，1为正常，0为异常
       * </pre>
       *
       * <code>optional string type = 9;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *类型，1为正常，0为异常
       * </pre>
       *
       * <code>optional string type = 9;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *类型，1为正常，0为异常
       * </pre>
       *
       * <code>optional string type = 9;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.wolf.javabean.Logs)
    }

    // @@protoc_insertion_point(class_scope:com.wolf.javabean.Logs)
    private static final com.wolf.javabean.LogBean.Logs DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wolf.javabean.LogBean.Logs();
    }

    public static com.wolf.javabean.LogBean.Logs getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Logs>
        PARSER = new com.google.protobuf.AbstractParser<Logs>() {
      public Logs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Logs(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Logs> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Logs> getParserForType() {
      return PARSER;
    }

    public com.wolf.javabean.LogBean.Logs getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wolf_javabean_LogDatas_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wolf_javabean_LogDatas_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wolf_javabean_Logs_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wolf_javabean_Logs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rLogBean.proto\022\021com.wolf.javabean\"1\n\010Lo" +
      "gDatas\022%\n\004logs\030\001 \001(\0132\027.com.wolf.javabean" +
      ".Logs\"\217\001\n\004Logs\022\016\n\006mainId\030\001 \001(\t\022\020\n\010parent" +
      "Id\030\002 \001(\t\022\n\n\002id\030\003 \001(\t\022\014\n\004time\030\004 \001(\t\022\017\n\007me" +
      "ssage\030\005 \001(\t\022\014\n\004path\030\006 \001(\t\022\022\n\nserverName\030" +
      "\007 \001(\t\022\n\n\002ip\030\010 \001(\t\022\014\n\004type\030\t \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_wolf_javabean_LogDatas_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wolf_javabean_LogDatas_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wolf_javabean_LogDatas_descriptor,
        new java.lang.String[] { "Logs", });
    internal_static_com_wolf_javabean_Logs_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_wolf_javabean_Logs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wolf_javabean_Logs_descriptor,
        new java.lang.String[] { "MainId", "ParentId", "Id", "Time", "Message", "Path", "ServerName", "Ip", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
