// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TranNet.proto

package com.wolf.javabean;

public final class TranNet {
  private TranNet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransDatasOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wolf.javabean.TransDatas)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.wolf.javabean.Trans trans = 1;</code>
     */
    boolean hasTrans();
    /**
     * <code>optional .com.wolf.javabean.Trans trans = 1;</code>
     */
    com.wolf.javabean.TranNet.Trans getTrans();
    /**
     * <code>optional .com.wolf.javabean.Trans trans = 1;</code>
     */
    com.wolf.javabean.TranNet.TransOrBuilder getTransOrBuilder();

    /**
     * <code>optional .com.wolf.javabean.LineLog lineLog = 2;</code>
     */
    boolean hasLineLog();
    /**
     * <code>optional .com.wolf.javabean.LineLog lineLog = 2;</code>
     */
    com.wolf.javabean.TranNet.LineLog getLineLog();
    /**
     * <code>optional .com.wolf.javabean.LineLog lineLog = 2;</code>
     */
    com.wolf.javabean.TranNet.LineLogOrBuilder getLineLogOrBuilder();
  }
  /**
   * Protobuf type {@code com.wolf.javabean.TransDatas}
   */
  public  static final class TransDatas extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.wolf.javabean.TransDatas)
      TransDatasOrBuilder {
    // Use TransDatas.newBuilder() to construct.
    private TransDatas(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransDatas() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TransDatas(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.wolf.javabean.TranNet.Trans.Builder subBuilder = null;
              if (trans_ != null) {
                subBuilder = trans_.toBuilder();
              }
              trans_ = input.readMessage(com.wolf.javabean.TranNet.Trans.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(trans_);
                trans_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.wolf.javabean.TranNet.LineLog.Builder subBuilder = null;
              if (lineLog_ != null) {
                subBuilder = lineLog_.toBuilder();
              }
              lineLog_ = input.readMessage(com.wolf.javabean.TranNet.LineLog.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lineLog_);
                lineLog_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wolf.javabean.TranNet.internal_static_com_wolf_javabean_TransDatas_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wolf.javabean.TranNet.internal_static_com_wolf_javabean_TransDatas_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wolf.javabean.TranNet.TransDatas.class, com.wolf.javabean.TranNet.TransDatas.Builder.class);
    }

    public static final int TRANS_FIELD_NUMBER = 1;
    private com.wolf.javabean.TranNet.Trans trans_;
    /**
     * <code>optional .com.wolf.javabean.Trans trans = 1;</code>
     */
    public boolean hasTrans() {
      return trans_ != null;
    }
    /**
     * <code>optional .com.wolf.javabean.Trans trans = 1;</code>
     */
    public com.wolf.javabean.TranNet.Trans getTrans() {
      return trans_ == null ? com.wolf.javabean.TranNet.Trans.getDefaultInstance() : trans_;
    }
    /**
     * <code>optional .com.wolf.javabean.Trans trans = 1;</code>
     */
    public com.wolf.javabean.TranNet.TransOrBuilder getTransOrBuilder() {
      return getTrans();
    }

    public static final int LINELOG_FIELD_NUMBER = 2;
    private com.wolf.javabean.TranNet.LineLog lineLog_;
    /**
     * <code>optional .com.wolf.javabean.LineLog lineLog = 2;</code>
     */
    public boolean hasLineLog() {
      return lineLog_ != null;
    }
    /**
     * <code>optional .com.wolf.javabean.LineLog lineLog = 2;</code>
     */
    public com.wolf.javabean.TranNet.LineLog getLineLog() {
      return lineLog_ == null ? com.wolf.javabean.TranNet.LineLog.getDefaultInstance() : lineLog_;
    }
    /**
     * <code>optional .com.wolf.javabean.LineLog lineLog = 2;</code>
     */
    public com.wolf.javabean.TranNet.LineLogOrBuilder getLineLogOrBuilder() {
      return getLineLog();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (trans_ != null) {
        output.writeMessage(1, getTrans());
      }
      if (lineLog_ != null) {
        output.writeMessage(2, getLineLog());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (trans_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTrans());
      }
      if (lineLog_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLineLog());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wolf.javabean.TranNet.TransDatas)) {
        return super.equals(obj);
      }
      com.wolf.javabean.TranNet.TransDatas other = (com.wolf.javabean.TranNet.TransDatas) obj;

      boolean result = true;
      result = result && (hasTrans() == other.hasTrans());
      if (hasTrans()) {
        result = result && getTrans()
            .equals(other.getTrans());
      }
      result = result && (hasLineLog() == other.hasLineLog());
      if (hasLineLog()) {
        result = result && getLineLog()
            .equals(other.getLineLog());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTrans()) {
        hash = (37 * hash) + TRANS_FIELD_NUMBER;
        hash = (53 * hash) + getTrans().hashCode();
      }
      if (hasLineLog()) {
        hash = (37 * hash) + LINELOG_FIELD_NUMBER;
        hash = (53 * hash) + getLineLog().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wolf.javabean.TranNet.TransDatas parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.TranNet.TransDatas parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.TranNet.TransDatas parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.TranNet.TransDatas parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.TranNet.TransDatas parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.TranNet.TransDatas parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.TranNet.TransDatas parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.TranNet.TransDatas parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.TranNet.TransDatas parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.TranNet.TransDatas parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wolf.javabean.TranNet.TransDatas prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wolf.javabean.TransDatas}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wolf.javabean.TransDatas)
        com.wolf.javabean.TranNet.TransDatasOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wolf.javabean.TranNet.internal_static_com_wolf_javabean_TransDatas_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wolf.javabean.TranNet.internal_static_com_wolf_javabean_TransDatas_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wolf.javabean.TranNet.TransDatas.class, com.wolf.javabean.TranNet.TransDatas.Builder.class);
      }

      // Construct using com.wolf.javabean.TranNet.TransDatas.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (transBuilder_ == null) {
          trans_ = null;
        } else {
          trans_ = null;
          transBuilder_ = null;
        }
        if (lineLogBuilder_ == null) {
          lineLog_ = null;
        } else {
          lineLog_ = null;
          lineLogBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wolf.javabean.TranNet.internal_static_com_wolf_javabean_TransDatas_descriptor;
      }

      public com.wolf.javabean.TranNet.TransDatas getDefaultInstanceForType() {
        return com.wolf.javabean.TranNet.TransDatas.getDefaultInstance();
      }

      public com.wolf.javabean.TranNet.TransDatas build() {
        com.wolf.javabean.TranNet.TransDatas result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wolf.javabean.TranNet.TransDatas buildPartial() {
        com.wolf.javabean.TranNet.TransDatas result = new com.wolf.javabean.TranNet.TransDatas(this);
        if (transBuilder_ == null) {
          result.trans_ = trans_;
        } else {
          result.trans_ = transBuilder_.build();
        }
        if (lineLogBuilder_ == null) {
          result.lineLog_ = lineLog_;
        } else {
          result.lineLog_ = lineLogBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wolf.javabean.TranNet.TransDatas) {
          return mergeFrom((com.wolf.javabean.TranNet.TransDatas)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wolf.javabean.TranNet.TransDatas other) {
        if (other == com.wolf.javabean.TranNet.TransDatas.getDefaultInstance()) return this;
        if (other.hasTrans()) {
          mergeTrans(other.getTrans());
        }
        if (other.hasLineLog()) {
          mergeLineLog(other.getLineLog());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wolf.javabean.TranNet.TransDatas parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wolf.javabean.TranNet.TransDatas) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.wolf.javabean.TranNet.Trans trans_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolf.javabean.TranNet.Trans, com.wolf.javabean.TranNet.Trans.Builder, com.wolf.javabean.TranNet.TransOrBuilder> transBuilder_;
      /**
       * <code>optional .com.wolf.javabean.Trans trans = 1;</code>
       */
      public boolean hasTrans() {
        return transBuilder_ != null || trans_ != null;
      }
      /**
       * <code>optional .com.wolf.javabean.Trans trans = 1;</code>
       */
      public com.wolf.javabean.TranNet.Trans getTrans() {
        if (transBuilder_ == null) {
          return trans_ == null ? com.wolf.javabean.TranNet.Trans.getDefaultInstance() : trans_;
        } else {
          return transBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.wolf.javabean.Trans trans = 1;</code>
       */
      public Builder setTrans(com.wolf.javabean.TranNet.Trans value) {
        if (transBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          trans_ = value;
          onChanged();
        } else {
          transBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Trans trans = 1;</code>
       */
      public Builder setTrans(
          com.wolf.javabean.TranNet.Trans.Builder builderForValue) {
        if (transBuilder_ == null) {
          trans_ = builderForValue.build();
          onChanged();
        } else {
          transBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Trans trans = 1;</code>
       */
      public Builder mergeTrans(com.wolf.javabean.TranNet.Trans value) {
        if (transBuilder_ == null) {
          if (trans_ != null) {
            trans_ =
              com.wolf.javabean.TranNet.Trans.newBuilder(trans_).mergeFrom(value).buildPartial();
          } else {
            trans_ = value;
          }
          onChanged();
        } else {
          transBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Trans trans = 1;</code>
       */
      public Builder clearTrans() {
        if (transBuilder_ == null) {
          trans_ = null;
          onChanged();
        } else {
          trans_ = null;
          transBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Trans trans = 1;</code>
       */
      public com.wolf.javabean.TranNet.Trans.Builder getTransBuilder() {
        
        onChanged();
        return getTransFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.wolf.javabean.Trans trans = 1;</code>
       */
      public com.wolf.javabean.TranNet.TransOrBuilder getTransOrBuilder() {
        if (transBuilder_ != null) {
          return transBuilder_.getMessageOrBuilder();
        } else {
          return trans_ == null ?
              com.wolf.javabean.TranNet.Trans.getDefaultInstance() : trans_;
        }
      }
      /**
       * <code>optional .com.wolf.javabean.Trans trans = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolf.javabean.TranNet.Trans, com.wolf.javabean.TranNet.Trans.Builder, com.wolf.javabean.TranNet.TransOrBuilder> 
          getTransFieldBuilder() {
        if (transBuilder_ == null) {
          transBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wolf.javabean.TranNet.Trans, com.wolf.javabean.TranNet.Trans.Builder, com.wolf.javabean.TranNet.TransOrBuilder>(
                  getTrans(),
                  getParentForChildren(),
                  isClean());
          trans_ = null;
        }
        return transBuilder_;
      }

      private com.wolf.javabean.TranNet.LineLog lineLog_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolf.javabean.TranNet.LineLog, com.wolf.javabean.TranNet.LineLog.Builder, com.wolf.javabean.TranNet.LineLogOrBuilder> lineLogBuilder_;
      /**
       * <code>optional .com.wolf.javabean.LineLog lineLog = 2;</code>
       */
      public boolean hasLineLog() {
        return lineLogBuilder_ != null || lineLog_ != null;
      }
      /**
       * <code>optional .com.wolf.javabean.LineLog lineLog = 2;</code>
       */
      public com.wolf.javabean.TranNet.LineLog getLineLog() {
        if (lineLogBuilder_ == null) {
          return lineLog_ == null ? com.wolf.javabean.TranNet.LineLog.getDefaultInstance() : lineLog_;
        } else {
          return lineLogBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.wolf.javabean.LineLog lineLog = 2;</code>
       */
      public Builder setLineLog(com.wolf.javabean.TranNet.LineLog value) {
        if (lineLogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lineLog_ = value;
          onChanged();
        } else {
          lineLogBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.LineLog lineLog = 2;</code>
       */
      public Builder setLineLog(
          com.wolf.javabean.TranNet.LineLog.Builder builderForValue) {
        if (lineLogBuilder_ == null) {
          lineLog_ = builderForValue.build();
          onChanged();
        } else {
          lineLogBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.LineLog lineLog = 2;</code>
       */
      public Builder mergeLineLog(com.wolf.javabean.TranNet.LineLog value) {
        if (lineLogBuilder_ == null) {
          if (lineLog_ != null) {
            lineLog_ =
              com.wolf.javabean.TranNet.LineLog.newBuilder(lineLog_).mergeFrom(value).buildPartial();
          } else {
            lineLog_ = value;
          }
          onChanged();
        } else {
          lineLogBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.LineLog lineLog = 2;</code>
       */
      public Builder clearLineLog() {
        if (lineLogBuilder_ == null) {
          lineLog_ = null;
          onChanged();
        } else {
          lineLog_ = null;
          lineLogBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.LineLog lineLog = 2;</code>
       */
      public com.wolf.javabean.TranNet.LineLog.Builder getLineLogBuilder() {
        
        onChanged();
        return getLineLogFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.wolf.javabean.LineLog lineLog = 2;</code>
       */
      public com.wolf.javabean.TranNet.LineLogOrBuilder getLineLogOrBuilder() {
        if (lineLogBuilder_ != null) {
          return lineLogBuilder_.getMessageOrBuilder();
        } else {
          return lineLog_ == null ?
              com.wolf.javabean.TranNet.LineLog.getDefaultInstance() : lineLog_;
        }
      }
      /**
       * <code>optional .com.wolf.javabean.LineLog lineLog = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolf.javabean.TranNet.LineLog, com.wolf.javabean.TranNet.LineLog.Builder, com.wolf.javabean.TranNet.LineLogOrBuilder> 
          getLineLogFieldBuilder() {
        if (lineLogBuilder_ == null) {
          lineLogBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wolf.javabean.TranNet.LineLog, com.wolf.javabean.TranNet.LineLog.Builder, com.wolf.javabean.TranNet.LineLogOrBuilder>(
                  getLineLog(),
                  getParentForChildren(),
                  isClean());
          lineLog_ = null;
        }
        return lineLogBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.wolf.javabean.TransDatas)
    }

    // @@protoc_insertion_point(class_scope:com.wolf.javabean.TransDatas)
    private static final com.wolf.javabean.TranNet.TransDatas DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wolf.javabean.TranNet.TransDatas();
    }

    public static com.wolf.javabean.TranNet.TransDatas getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransDatas>
        PARSER = new com.google.protobuf.AbstractParser<TransDatas>() {
      public TransDatas parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TransDatas(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransDatas> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransDatas> getParserForType() {
      return PARSER;
    }

    public com.wolf.javabean.TranNet.TransDatas getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wolf.javabean.Trans)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *是否确认本次
     * </pre>
     *
     * <code>optional bool trans = 1;</code>
     */
    boolean getTrans();

    /**
     * <code>optional sint64 tranCommitMinute = 2;</code>
     */
    long getTranCommitMinute();

    /**
     * <code>optional sint64 tranRollbackMinute = 3;</code>
     */
    long getTranRollbackMinute();

    /**
     * <pre>
     *主控id
     * </pre>
     *
     * <code>optional string mainId = 4;</code>
     */
    java.lang.String getMainId();
    /**
     * <pre>
     *主控id
     * </pre>
     *
     * <code>optional string mainId = 4;</code>
     */
    com.google.protobuf.ByteString
        getMainIdBytes();

    /**
     * <pre>
     *业务id
     * </pre>
     *
     * <code>optional string serverId = 5;</code>
     */
    java.lang.String getServerId();
    /**
     * <pre>
     *业务id
     * </pre>
     *
     * <code>optional string serverId = 5;</code>
     */
    com.google.protobuf.ByteString
        getServerIdBytes();

    /**
     * <pre>
     *确认类型，判断哪次提交(canCommit,commiting,commitend)
     * </pre>
     *
     * <code>optional string type = 6;</code>
     */
    java.lang.String getType();
    /**
     * <pre>
     *确认类型，判断哪次提交(canCommit,commiting,commitend)
     * </pre>
     *
     * <code>optional string type = 6;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     *是否主控
     * </pre>
     *
     * <code>optional bool ismain = 7;</code>
     */
    boolean getIsmain();

    /**
     * <pre>
     *是否补偿
     * </pre>
     *
     * <code>optional bool compensate = 8;</code>
     */
    boolean getCompensate();

    /**
     * <pre>
     *0回滚，1是提交
     * </pre>
     *
     * <code>optional sint64 status = 9;</code>
     */
    long getStatus();
  }
  /**
   * Protobuf type {@code com.wolf.javabean.Trans}
   */
  public  static final class Trans extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.wolf.javabean.Trans)
      TransOrBuilder {
    // Use Trans.newBuilder() to construct.
    private Trans(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Trans() {
      trans_ = false;
      tranCommitMinute_ = 0L;
      tranRollbackMinute_ = 0L;
      mainId_ = "";
      serverId_ = "";
      type_ = "";
      ismain_ = false;
      compensate_ = false;
      status_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Trans(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              trans_ = input.readBool();
              break;
            }
            case 16: {

              tranCommitMinute_ = input.readSInt64();
              break;
            }
            case 24: {

              tranRollbackMinute_ = input.readSInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              mainId_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              serverId_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 56: {

              ismain_ = input.readBool();
              break;
            }
            case 64: {

              compensate_ = input.readBool();
              break;
            }
            case 72: {

              status_ = input.readSInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wolf.javabean.TranNet.internal_static_com_wolf_javabean_Trans_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wolf.javabean.TranNet.internal_static_com_wolf_javabean_Trans_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wolf.javabean.TranNet.Trans.class, com.wolf.javabean.TranNet.Trans.Builder.class);
    }

    public static final int TRANS_FIELD_NUMBER = 1;
    private boolean trans_;
    /**
     * <pre>
     *是否确认本次
     * </pre>
     *
     * <code>optional bool trans = 1;</code>
     */
    public boolean getTrans() {
      return trans_;
    }

    public static final int TRANCOMMITMINUTE_FIELD_NUMBER = 2;
    private long tranCommitMinute_;
    /**
     * <code>optional sint64 tranCommitMinute = 2;</code>
     */
    public long getTranCommitMinute() {
      return tranCommitMinute_;
    }

    public static final int TRANROLLBACKMINUTE_FIELD_NUMBER = 3;
    private long tranRollbackMinute_;
    /**
     * <code>optional sint64 tranRollbackMinute = 3;</code>
     */
    public long getTranRollbackMinute() {
      return tranRollbackMinute_;
    }

    public static final int MAINID_FIELD_NUMBER = 4;
    private volatile java.lang.Object mainId_;
    /**
     * <pre>
     *主控id
     * </pre>
     *
     * <code>optional string mainId = 4;</code>
     */
    public java.lang.String getMainId() {
      java.lang.Object ref = mainId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mainId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *主控id
     * </pre>
     *
     * <code>optional string mainId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMainIdBytes() {
      java.lang.Object ref = mainId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mainId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERID_FIELD_NUMBER = 5;
    private volatile java.lang.Object serverId_;
    /**
     * <pre>
     *业务id
     * </pre>
     *
     * <code>optional string serverId = 5;</code>
     */
    public java.lang.String getServerId() {
      java.lang.Object ref = serverId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *业务id
     * </pre>
     *
     * <code>optional string serverId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getServerIdBytes() {
      java.lang.Object ref = serverId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 6;
    private volatile java.lang.Object type_;
    /**
     * <pre>
     *确认类型，判断哪次提交(canCommit,commiting,commitend)
     * </pre>
     *
     * <code>optional string type = 6;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *确认类型，判断哪次提交(canCommit,commiting,commitend)
     * </pre>
     *
     * <code>optional string type = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISMAIN_FIELD_NUMBER = 7;
    private boolean ismain_;
    /**
     * <pre>
     *是否主控
     * </pre>
     *
     * <code>optional bool ismain = 7;</code>
     */
    public boolean getIsmain() {
      return ismain_;
    }

    public static final int COMPENSATE_FIELD_NUMBER = 8;
    private boolean compensate_;
    /**
     * <pre>
     *是否补偿
     * </pre>
     *
     * <code>optional bool compensate = 8;</code>
     */
    public boolean getCompensate() {
      return compensate_;
    }

    public static final int STATUS_FIELD_NUMBER = 9;
    private long status_;
    /**
     * <pre>
     *0回滚，1是提交
     * </pre>
     *
     * <code>optional sint64 status = 9;</code>
     */
    public long getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (trans_ != false) {
        output.writeBool(1, trans_);
      }
      if (tranCommitMinute_ != 0L) {
        output.writeSInt64(2, tranCommitMinute_);
      }
      if (tranRollbackMinute_ != 0L) {
        output.writeSInt64(3, tranRollbackMinute_);
      }
      if (!getMainIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mainId_);
      }
      if (!getServerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, serverId_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, type_);
      }
      if (ismain_ != false) {
        output.writeBool(7, ismain_);
      }
      if (compensate_ != false) {
        output.writeBool(8, compensate_);
      }
      if (status_ != 0L) {
        output.writeSInt64(9, status_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (trans_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, trans_);
      }
      if (tranCommitMinute_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(2, tranCommitMinute_);
      }
      if (tranRollbackMinute_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(3, tranRollbackMinute_);
      }
      if (!getMainIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mainId_);
      }
      if (!getServerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, serverId_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, type_);
      }
      if (ismain_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, ismain_);
      }
      if (compensate_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, compensate_);
      }
      if (status_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(9, status_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wolf.javabean.TranNet.Trans)) {
        return super.equals(obj);
      }
      com.wolf.javabean.TranNet.Trans other = (com.wolf.javabean.TranNet.Trans) obj;

      boolean result = true;
      result = result && (getTrans()
          == other.getTrans());
      result = result && (getTranCommitMinute()
          == other.getTranCommitMinute());
      result = result && (getTranRollbackMinute()
          == other.getTranRollbackMinute());
      result = result && getMainId()
          .equals(other.getMainId());
      result = result && getServerId()
          .equals(other.getServerId());
      result = result && getType()
          .equals(other.getType());
      result = result && (getIsmain()
          == other.getIsmain());
      result = result && (getCompensate()
          == other.getCompensate());
      result = result && (getStatus()
          == other.getStatus());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TRANS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getTrans());
      hash = (37 * hash) + TRANCOMMITMINUTE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTranCommitMinute());
      hash = (37 * hash) + TRANROLLBACKMINUTE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTranRollbackMinute());
      hash = (37 * hash) + MAINID_FIELD_NUMBER;
      hash = (53 * hash) + getMainId().hashCode();
      hash = (37 * hash) + SERVERID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + ISMAIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsmain());
      hash = (37 * hash) + COMPENSATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCompensate());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStatus());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wolf.javabean.TranNet.Trans parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.TranNet.Trans parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.TranNet.Trans parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.TranNet.Trans parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.TranNet.Trans parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.TranNet.Trans parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.TranNet.Trans parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.TranNet.Trans parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.TranNet.Trans parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.TranNet.Trans parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wolf.javabean.TranNet.Trans prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wolf.javabean.Trans}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wolf.javabean.Trans)
        com.wolf.javabean.TranNet.TransOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wolf.javabean.TranNet.internal_static_com_wolf_javabean_Trans_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wolf.javabean.TranNet.internal_static_com_wolf_javabean_Trans_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wolf.javabean.TranNet.Trans.class, com.wolf.javabean.TranNet.Trans.Builder.class);
      }

      // Construct using com.wolf.javabean.TranNet.Trans.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        trans_ = false;

        tranCommitMinute_ = 0L;

        tranRollbackMinute_ = 0L;

        mainId_ = "";

        serverId_ = "";

        type_ = "";

        ismain_ = false;

        compensate_ = false;

        status_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wolf.javabean.TranNet.internal_static_com_wolf_javabean_Trans_descriptor;
      }

      public com.wolf.javabean.TranNet.Trans getDefaultInstanceForType() {
        return com.wolf.javabean.TranNet.Trans.getDefaultInstance();
      }

      public com.wolf.javabean.TranNet.Trans build() {
        com.wolf.javabean.TranNet.Trans result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wolf.javabean.TranNet.Trans buildPartial() {
        com.wolf.javabean.TranNet.Trans result = new com.wolf.javabean.TranNet.Trans(this);
        result.trans_ = trans_;
        result.tranCommitMinute_ = tranCommitMinute_;
        result.tranRollbackMinute_ = tranRollbackMinute_;
        result.mainId_ = mainId_;
        result.serverId_ = serverId_;
        result.type_ = type_;
        result.ismain_ = ismain_;
        result.compensate_ = compensate_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wolf.javabean.TranNet.Trans) {
          return mergeFrom((com.wolf.javabean.TranNet.Trans)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wolf.javabean.TranNet.Trans other) {
        if (other == com.wolf.javabean.TranNet.Trans.getDefaultInstance()) return this;
        if (other.getTrans() != false) {
          setTrans(other.getTrans());
        }
        if (other.getTranCommitMinute() != 0L) {
          setTranCommitMinute(other.getTranCommitMinute());
        }
        if (other.getTranRollbackMinute() != 0L) {
          setTranRollbackMinute(other.getTranRollbackMinute());
        }
        if (!other.getMainId().isEmpty()) {
          mainId_ = other.mainId_;
          onChanged();
        }
        if (!other.getServerId().isEmpty()) {
          serverId_ = other.serverId_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getIsmain() != false) {
          setIsmain(other.getIsmain());
        }
        if (other.getCompensate() != false) {
          setCompensate(other.getCompensate());
        }
        if (other.getStatus() != 0L) {
          setStatus(other.getStatus());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wolf.javabean.TranNet.Trans parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wolf.javabean.TranNet.Trans) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean trans_ ;
      /**
       * <pre>
       *是否确认本次
       * </pre>
       *
       * <code>optional bool trans = 1;</code>
       */
      public boolean getTrans() {
        return trans_;
      }
      /**
       * <pre>
       *是否确认本次
       * </pre>
       *
       * <code>optional bool trans = 1;</code>
       */
      public Builder setTrans(boolean value) {
        
        trans_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否确认本次
       * </pre>
       *
       * <code>optional bool trans = 1;</code>
       */
      public Builder clearTrans() {
        
        trans_ = false;
        onChanged();
        return this;
      }

      private long tranCommitMinute_ ;
      /**
       * <code>optional sint64 tranCommitMinute = 2;</code>
       */
      public long getTranCommitMinute() {
        return tranCommitMinute_;
      }
      /**
       * <code>optional sint64 tranCommitMinute = 2;</code>
       */
      public Builder setTranCommitMinute(long value) {
        
        tranCommitMinute_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 tranCommitMinute = 2;</code>
       */
      public Builder clearTranCommitMinute() {
        
        tranCommitMinute_ = 0L;
        onChanged();
        return this;
      }

      private long tranRollbackMinute_ ;
      /**
       * <code>optional sint64 tranRollbackMinute = 3;</code>
       */
      public long getTranRollbackMinute() {
        return tranRollbackMinute_;
      }
      /**
       * <code>optional sint64 tranRollbackMinute = 3;</code>
       */
      public Builder setTranRollbackMinute(long value) {
        
        tranRollbackMinute_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 tranRollbackMinute = 3;</code>
       */
      public Builder clearTranRollbackMinute() {
        
        tranRollbackMinute_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object mainId_ = "";
      /**
       * <pre>
       *主控id
       * </pre>
       *
       * <code>optional string mainId = 4;</code>
       */
      public java.lang.String getMainId() {
        java.lang.Object ref = mainId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mainId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *主控id
       * </pre>
       *
       * <code>optional string mainId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMainIdBytes() {
        java.lang.Object ref = mainId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mainId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *主控id
       * </pre>
       *
       * <code>optional string mainId = 4;</code>
       */
      public Builder setMainId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mainId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主控id
       * </pre>
       *
       * <code>optional string mainId = 4;</code>
       */
      public Builder clearMainId() {
        
        mainId_ = getDefaultInstance().getMainId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主控id
       * </pre>
       *
       * <code>optional string mainId = 4;</code>
       */
      public Builder setMainIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mainId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serverId_ = "";
      /**
       * <pre>
       *业务id
       * </pre>
       *
       * <code>optional string serverId = 5;</code>
       */
      public java.lang.String getServerId() {
        java.lang.Object ref = serverId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *业务id
       * </pre>
       *
       * <code>optional string serverId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getServerIdBytes() {
        java.lang.Object ref = serverId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *业务id
       * </pre>
       *
       * <code>optional string serverId = 5;</code>
       */
      public Builder setServerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *业务id
       * </pre>
       *
       * <code>optional string serverId = 5;</code>
       */
      public Builder clearServerId() {
        
        serverId_ = getDefaultInstance().getServerId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *业务id
       * </pre>
       *
       * <code>optional string serverId = 5;</code>
       */
      public Builder setServerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <pre>
       *确认类型，判断哪次提交(canCommit,commiting,commitend)
       * </pre>
       *
       * <code>optional string type = 6;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *确认类型，判断哪次提交(canCommit,commiting,commitend)
       * </pre>
       *
       * <code>optional string type = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *确认类型，判断哪次提交(canCommit,commiting,commitend)
       * </pre>
       *
       * <code>optional string type = 6;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *确认类型，判断哪次提交(canCommit,commiting,commitend)
       * </pre>
       *
       * <code>optional string type = 6;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *确认类型，判断哪次提交(canCommit,commiting,commitend)
       * </pre>
       *
       * <code>optional string type = 6;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private boolean ismain_ ;
      /**
       * <pre>
       *是否主控
       * </pre>
       *
       * <code>optional bool ismain = 7;</code>
       */
      public boolean getIsmain() {
        return ismain_;
      }
      /**
       * <pre>
       *是否主控
       * </pre>
       *
       * <code>optional bool ismain = 7;</code>
       */
      public Builder setIsmain(boolean value) {
        
        ismain_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否主控
       * </pre>
       *
       * <code>optional bool ismain = 7;</code>
       */
      public Builder clearIsmain() {
        
        ismain_ = false;
        onChanged();
        return this;
      }

      private boolean compensate_ ;
      /**
       * <pre>
       *是否补偿
       * </pre>
       *
       * <code>optional bool compensate = 8;</code>
       */
      public boolean getCompensate() {
        return compensate_;
      }
      /**
       * <pre>
       *是否补偿
       * </pre>
       *
       * <code>optional bool compensate = 8;</code>
       */
      public Builder setCompensate(boolean value) {
        
        compensate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否补偿
       * </pre>
       *
       * <code>optional bool compensate = 8;</code>
       */
      public Builder clearCompensate() {
        
        compensate_ = false;
        onChanged();
        return this;
      }

      private long status_ ;
      /**
       * <pre>
       *0回滚，1是提交
       * </pre>
       *
       * <code>optional sint64 status = 9;</code>
       */
      public long getStatus() {
        return status_;
      }
      /**
       * <pre>
       *0回滚，1是提交
       * </pre>
       *
       * <code>optional sint64 status = 9;</code>
       */
      public Builder setStatus(long value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0回滚，1是提交
       * </pre>
       *
       * <code>optional sint64 status = 9;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.wolf.javabean.Trans)
    }

    // @@protoc_insertion_point(class_scope:com.wolf.javabean.Trans)
    private static final com.wolf.javabean.TranNet.Trans DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wolf.javabean.TranNet.Trans();
    }

    public static com.wolf.javabean.TranNet.Trans getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Trans>
        PARSER = new com.google.protobuf.AbstractParser<Trans>() {
      public Trans parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Trans(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Trans> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Trans> getParserForType() {
      return PARSER;
    }

    public com.wolf.javabean.TranNet.Trans getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LineLogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wolf.javabean.LineLog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string mainId = 1;</code>
     */
    java.lang.String getMainId();
    /**
     * <code>optional string mainId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMainIdBytes();

    /**
     * <code>optional string parentId = 2;</code>
     */
    java.lang.String getParentId();
    /**
     * <code>optional string parentId = 2;</code>
     */
    com.google.protobuf.ByteString
        getParentIdBytes();

    /**
     * <code>optional string id = 3;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 3;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * <pre>
   *调用链日志
   * </pre>
   *
   * Protobuf type {@code com.wolf.javabean.LineLog}
   */
  public  static final class LineLog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.wolf.javabean.LineLog)
      LineLogOrBuilder {
    // Use LineLog.newBuilder() to construct.
    private LineLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LineLog() {
      mainId_ = "";
      parentId_ = "";
      id_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LineLog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              mainId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              parentId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wolf.javabean.TranNet.internal_static_com_wolf_javabean_LineLog_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wolf.javabean.TranNet.internal_static_com_wolf_javabean_LineLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wolf.javabean.TranNet.LineLog.class, com.wolf.javabean.TranNet.LineLog.Builder.class);
    }

    public static final int MAINID_FIELD_NUMBER = 1;
    private volatile java.lang.Object mainId_;
    /**
     * <code>optional string mainId = 1;</code>
     */
    public java.lang.String getMainId() {
      java.lang.Object ref = mainId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mainId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string mainId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMainIdBytes() {
      java.lang.Object ref = mainId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mainId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARENTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object parentId_;
    /**
     * <code>optional string parentId = 2;</code>
     */
    public java.lang.String getParentId() {
      java.lang.Object ref = parentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string parentId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getParentIdBytes() {
      java.lang.Object ref = parentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 3;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>optional string id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMainIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mainId_);
      }
      if (!getParentIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, parentId_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, id_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMainIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mainId_);
      }
      if (!getParentIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, parentId_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, id_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wolf.javabean.TranNet.LineLog)) {
        return super.equals(obj);
      }
      com.wolf.javabean.TranNet.LineLog other = (com.wolf.javabean.TranNet.LineLog) obj;

      boolean result = true;
      result = result && getMainId()
          .equals(other.getMainId());
      result = result && getParentId()
          .equals(other.getParentId());
      result = result && getId()
          .equals(other.getId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + MAINID_FIELD_NUMBER;
      hash = (53 * hash) + getMainId().hashCode();
      hash = (37 * hash) + PARENTID_FIELD_NUMBER;
      hash = (53 * hash) + getParentId().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wolf.javabean.TranNet.LineLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.TranNet.LineLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.TranNet.LineLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.TranNet.LineLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.TranNet.LineLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.TranNet.LineLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.TranNet.LineLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.TranNet.LineLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.TranNet.LineLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.TranNet.LineLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wolf.javabean.TranNet.LineLog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *调用链日志
     * </pre>
     *
     * Protobuf type {@code com.wolf.javabean.LineLog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wolf.javabean.LineLog)
        com.wolf.javabean.TranNet.LineLogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wolf.javabean.TranNet.internal_static_com_wolf_javabean_LineLog_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wolf.javabean.TranNet.internal_static_com_wolf_javabean_LineLog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wolf.javabean.TranNet.LineLog.class, com.wolf.javabean.TranNet.LineLog.Builder.class);
      }

      // Construct using com.wolf.javabean.TranNet.LineLog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        mainId_ = "";

        parentId_ = "";

        id_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wolf.javabean.TranNet.internal_static_com_wolf_javabean_LineLog_descriptor;
      }

      public com.wolf.javabean.TranNet.LineLog getDefaultInstanceForType() {
        return com.wolf.javabean.TranNet.LineLog.getDefaultInstance();
      }

      public com.wolf.javabean.TranNet.LineLog build() {
        com.wolf.javabean.TranNet.LineLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wolf.javabean.TranNet.LineLog buildPartial() {
        com.wolf.javabean.TranNet.LineLog result = new com.wolf.javabean.TranNet.LineLog(this);
        result.mainId_ = mainId_;
        result.parentId_ = parentId_;
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wolf.javabean.TranNet.LineLog) {
          return mergeFrom((com.wolf.javabean.TranNet.LineLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wolf.javabean.TranNet.LineLog other) {
        if (other == com.wolf.javabean.TranNet.LineLog.getDefaultInstance()) return this;
        if (!other.getMainId().isEmpty()) {
          mainId_ = other.mainId_;
          onChanged();
        }
        if (!other.getParentId().isEmpty()) {
          parentId_ = other.parentId_;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wolf.javabean.TranNet.LineLog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wolf.javabean.TranNet.LineLog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object mainId_ = "";
      /**
       * <code>optional string mainId = 1;</code>
       */
      public java.lang.String getMainId() {
        java.lang.Object ref = mainId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mainId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mainId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMainIdBytes() {
        java.lang.Object ref = mainId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mainId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mainId = 1;</code>
       */
      public Builder setMainId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mainId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mainId = 1;</code>
       */
      public Builder clearMainId() {
        
        mainId_ = getDefaultInstance().getMainId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mainId = 1;</code>
       */
      public Builder setMainIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mainId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object parentId_ = "";
      /**
       * <code>optional string parentId = 2;</code>
       */
      public java.lang.String getParentId() {
        java.lang.Object ref = parentId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          parentId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string parentId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getParentIdBytes() {
        java.lang.Object ref = parentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string parentId = 2;</code>
       */
      public Builder setParentId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        parentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string parentId = 2;</code>
       */
      public Builder clearParentId() {
        
        parentId_ = getDefaultInstance().getParentId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string parentId = 2;</code>
       */
      public Builder setParentIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        parentId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 3;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 3;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 3;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 3;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.wolf.javabean.LineLog)
    }

    // @@protoc_insertion_point(class_scope:com.wolf.javabean.LineLog)
    private static final com.wolf.javabean.TranNet.LineLog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wolf.javabean.TranNet.LineLog();
    }

    public static com.wolf.javabean.TranNet.LineLog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LineLog>
        PARSER = new com.google.protobuf.AbstractParser<LineLog>() {
      public LineLog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LineLog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LineLog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LineLog> getParserForType() {
      return PARSER;
    }

    public com.wolf.javabean.TranNet.LineLog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wolf_javabean_TransDatas_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wolf_javabean_TransDatas_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wolf_javabean_Trans_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wolf_javabean_Trans_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wolf_javabean_LineLog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wolf_javabean_LineLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rTranNet.proto\022\021com.wolf.javabean\"b\n\nTr" +
      "ansDatas\022\'\n\005trans\030\001 \001(\0132\030.com.wolf.javab" +
      "ean.Trans\022+\n\007lineLog\030\002 \001(\0132\032.com.wolf.ja" +
      "vabean.LineLog\"\260\001\n\005Trans\022\r\n\005trans\030\001 \001(\010\022" +
      "\030\n\020tranCommitMinute\030\002 \001(\022\022\032\n\022tranRollbac" +
      "kMinute\030\003 \001(\022\022\016\n\006mainId\030\004 \001(\t\022\020\n\010serverI" +
      "d\030\005 \001(\t\022\014\n\004type\030\006 \001(\t\022\016\n\006ismain\030\007 \001(\010\022\022\n" +
      "\ncompensate\030\010 \001(\010\022\016\n\006status\030\t \001(\022\"7\n\007Lin" +
      "eLog\022\016\n\006mainId\030\001 \001(\t\022\020\n\010parentId\030\002 \001(\t\022\n" +
      "\n\002id\030\003 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_wolf_javabean_TransDatas_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wolf_javabean_TransDatas_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wolf_javabean_TransDatas_descriptor,
        new java.lang.String[] { "Trans", "LineLog", });
    internal_static_com_wolf_javabean_Trans_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_wolf_javabean_Trans_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wolf_javabean_Trans_descriptor,
        new java.lang.String[] { "Trans", "TranCommitMinute", "TranRollbackMinute", "MainId", "ServerId", "Type", "Ismain", "Compensate", "Status", });
    internal_static_com_wolf_javabean_LineLog_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_wolf_javabean_LineLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wolf_javabean_LineLog_descriptor,
        new java.lang.String[] { "MainId", "ParentId", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
