// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Key.proto

package com.wolf.javabean;

public final class Key {
  private Key() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DatasOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wolf.javabean.Datas)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.wolf.javabean.Emcrypt emcrypt = 1;</code>
     */
    boolean hasEmcrypt();
    /**
     * <code>optional .com.wolf.javabean.Emcrypt emcrypt = 1;</code>
     */
    com.wolf.javabean.Key.Emcrypt getEmcrypt();
    /**
     * <code>optional .com.wolf.javabean.Emcrypt emcrypt = 1;</code>
     */
    com.wolf.javabean.Key.EmcryptOrBuilder getEmcryptOrBuilder();

    /**
     * <code>optional .com.wolf.javabean.Dmcrypt dmcrypt = 2;</code>
     */
    boolean hasDmcrypt();
    /**
     * <code>optional .com.wolf.javabean.Dmcrypt dmcrypt = 2;</code>
     */
    com.wolf.javabean.Key.Dmcrypt getDmcrypt();
    /**
     * <code>optional .com.wolf.javabean.Dmcrypt dmcrypt = 2;</code>
     */
    com.wolf.javabean.Key.DmcryptOrBuilder getDmcryptOrBuilder();

    /**
     * <pre>
     *2是用户密码请求加密,3是用户密码请求解密,-1是加密解密失败，1是加密解密成功
     * </pre>
     *
     * <code>optional string type = 3;</code>
     */
    java.lang.String getType();
    /**
     * <pre>
     *2是用户密码请求加密,3是用户密码请求解密,-1是加密解密失败，1是加密解密成功
     * </pre>
     *
     * <code>optional string type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>optional string id = 4;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 4;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code com.wolf.javabean.Datas}
   */
  public  static final class Datas extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.wolf.javabean.Datas)
      DatasOrBuilder {
    // Use Datas.newBuilder() to construct.
    private Datas(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Datas() {
      type_ = "";
      id_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Datas(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.wolf.javabean.Key.Emcrypt.Builder subBuilder = null;
              if (emcrypt_ != null) {
                subBuilder = emcrypt_.toBuilder();
              }
              emcrypt_ = input.readMessage(com.wolf.javabean.Key.Emcrypt.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(emcrypt_);
                emcrypt_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.wolf.javabean.Key.Dmcrypt.Builder subBuilder = null;
              if (dmcrypt_ != null) {
                subBuilder = dmcrypt_.toBuilder();
              }
              dmcrypt_ = input.readMessage(com.wolf.javabean.Key.Dmcrypt.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dmcrypt_);
                dmcrypt_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wolf.javabean.Key.internal_static_com_wolf_javabean_Datas_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wolf.javabean.Key.internal_static_com_wolf_javabean_Datas_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wolf.javabean.Key.Datas.class, com.wolf.javabean.Key.Datas.Builder.class);
    }

    public static final int EMCRYPT_FIELD_NUMBER = 1;
    private com.wolf.javabean.Key.Emcrypt emcrypt_;
    /**
     * <code>optional .com.wolf.javabean.Emcrypt emcrypt = 1;</code>
     */
    public boolean hasEmcrypt() {
      return emcrypt_ != null;
    }
    /**
     * <code>optional .com.wolf.javabean.Emcrypt emcrypt = 1;</code>
     */
    public com.wolf.javabean.Key.Emcrypt getEmcrypt() {
      return emcrypt_ == null ? com.wolf.javabean.Key.Emcrypt.getDefaultInstance() : emcrypt_;
    }
    /**
     * <code>optional .com.wolf.javabean.Emcrypt emcrypt = 1;</code>
     */
    public com.wolf.javabean.Key.EmcryptOrBuilder getEmcryptOrBuilder() {
      return getEmcrypt();
    }

    public static final int DMCRYPT_FIELD_NUMBER = 2;
    private com.wolf.javabean.Key.Dmcrypt dmcrypt_;
    /**
     * <code>optional .com.wolf.javabean.Dmcrypt dmcrypt = 2;</code>
     */
    public boolean hasDmcrypt() {
      return dmcrypt_ != null;
    }
    /**
     * <code>optional .com.wolf.javabean.Dmcrypt dmcrypt = 2;</code>
     */
    public com.wolf.javabean.Key.Dmcrypt getDmcrypt() {
      return dmcrypt_ == null ? com.wolf.javabean.Key.Dmcrypt.getDefaultInstance() : dmcrypt_;
    }
    /**
     * <code>optional .com.wolf.javabean.Dmcrypt dmcrypt = 2;</code>
     */
    public com.wolf.javabean.Key.DmcryptOrBuilder getDmcryptOrBuilder() {
      return getDmcrypt();
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object type_;
    /**
     * <pre>
     *2是用户密码请求加密,3是用户密码请求解密,-1是加密解密失败，1是加密解密成功
     * </pre>
     *
     * <code>optional string type = 3;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *2是用户密码请求加密,3是用户密码请求解密,-1是加密解密失败，1是加密解密成功
     * </pre>
     *
     * <code>optional string type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 4;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 4;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>optional string id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (emcrypt_ != null) {
        output.writeMessage(1, getEmcrypt());
      }
      if (dmcrypt_ != null) {
        output.writeMessage(2, getDmcrypt());
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, id_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (emcrypt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getEmcrypt());
      }
      if (dmcrypt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDmcrypt());
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, id_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wolf.javabean.Key.Datas)) {
        return super.equals(obj);
      }
      com.wolf.javabean.Key.Datas other = (com.wolf.javabean.Key.Datas) obj;

      boolean result = true;
      result = result && (hasEmcrypt() == other.hasEmcrypt());
      if (hasEmcrypt()) {
        result = result && getEmcrypt()
            .equals(other.getEmcrypt());
      }
      result = result && (hasDmcrypt() == other.hasDmcrypt());
      if (hasDmcrypt()) {
        result = result && getDmcrypt()
            .equals(other.getDmcrypt());
      }
      result = result && getType()
          .equals(other.getType());
      result = result && getId()
          .equals(other.getId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasEmcrypt()) {
        hash = (37 * hash) + EMCRYPT_FIELD_NUMBER;
        hash = (53 * hash) + getEmcrypt().hashCode();
      }
      if (hasDmcrypt()) {
        hash = (37 * hash) + DMCRYPT_FIELD_NUMBER;
        hash = (53 * hash) + getDmcrypt().hashCode();
      }
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wolf.javabean.Key.Datas parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.Key.Datas parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.Key.Datas parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.Key.Datas parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.Key.Datas parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.Key.Datas parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.Key.Datas parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.Key.Datas parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.Key.Datas parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.Key.Datas parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wolf.javabean.Key.Datas prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wolf.javabean.Datas}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wolf.javabean.Datas)
        com.wolf.javabean.Key.DatasOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wolf.javabean.Key.internal_static_com_wolf_javabean_Datas_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wolf.javabean.Key.internal_static_com_wolf_javabean_Datas_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wolf.javabean.Key.Datas.class, com.wolf.javabean.Key.Datas.Builder.class);
      }

      // Construct using com.wolf.javabean.Key.Datas.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (emcryptBuilder_ == null) {
          emcrypt_ = null;
        } else {
          emcrypt_ = null;
          emcryptBuilder_ = null;
        }
        if (dmcryptBuilder_ == null) {
          dmcrypt_ = null;
        } else {
          dmcrypt_ = null;
          dmcryptBuilder_ = null;
        }
        type_ = "";

        id_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wolf.javabean.Key.internal_static_com_wolf_javabean_Datas_descriptor;
      }

      public com.wolf.javabean.Key.Datas getDefaultInstanceForType() {
        return com.wolf.javabean.Key.Datas.getDefaultInstance();
      }

      public com.wolf.javabean.Key.Datas build() {
        com.wolf.javabean.Key.Datas result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wolf.javabean.Key.Datas buildPartial() {
        com.wolf.javabean.Key.Datas result = new com.wolf.javabean.Key.Datas(this);
        if (emcryptBuilder_ == null) {
          result.emcrypt_ = emcrypt_;
        } else {
          result.emcrypt_ = emcryptBuilder_.build();
        }
        if (dmcryptBuilder_ == null) {
          result.dmcrypt_ = dmcrypt_;
        } else {
          result.dmcrypt_ = dmcryptBuilder_.build();
        }
        result.type_ = type_;
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wolf.javabean.Key.Datas) {
          return mergeFrom((com.wolf.javabean.Key.Datas)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wolf.javabean.Key.Datas other) {
        if (other == com.wolf.javabean.Key.Datas.getDefaultInstance()) return this;
        if (other.hasEmcrypt()) {
          mergeEmcrypt(other.getEmcrypt());
        }
        if (other.hasDmcrypt()) {
          mergeDmcrypt(other.getDmcrypt());
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wolf.javabean.Key.Datas parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wolf.javabean.Key.Datas) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.wolf.javabean.Key.Emcrypt emcrypt_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolf.javabean.Key.Emcrypt, com.wolf.javabean.Key.Emcrypt.Builder, com.wolf.javabean.Key.EmcryptOrBuilder> emcryptBuilder_;
      /**
       * <code>optional .com.wolf.javabean.Emcrypt emcrypt = 1;</code>
       */
      public boolean hasEmcrypt() {
        return emcryptBuilder_ != null || emcrypt_ != null;
      }
      /**
       * <code>optional .com.wolf.javabean.Emcrypt emcrypt = 1;</code>
       */
      public com.wolf.javabean.Key.Emcrypt getEmcrypt() {
        if (emcryptBuilder_ == null) {
          return emcrypt_ == null ? com.wolf.javabean.Key.Emcrypt.getDefaultInstance() : emcrypt_;
        } else {
          return emcryptBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.wolf.javabean.Emcrypt emcrypt = 1;</code>
       */
      public Builder setEmcrypt(com.wolf.javabean.Key.Emcrypt value) {
        if (emcryptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          emcrypt_ = value;
          onChanged();
        } else {
          emcryptBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Emcrypt emcrypt = 1;</code>
       */
      public Builder setEmcrypt(
          com.wolf.javabean.Key.Emcrypt.Builder builderForValue) {
        if (emcryptBuilder_ == null) {
          emcrypt_ = builderForValue.build();
          onChanged();
        } else {
          emcryptBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Emcrypt emcrypt = 1;</code>
       */
      public Builder mergeEmcrypt(com.wolf.javabean.Key.Emcrypt value) {
        if (emcryptBuilder_ == null) {
          if (emcrypt_ != null) {
            emcrypt_ =
              com.wolf.javabean.Key.Emcrypt.newBuilder(emcrypt_).mergeFrom(value).buildPartial();
          } else {
            emcrypt_ = value;
          }
          onChanged();
        } else {
          emcryptBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Emcrypt emcrypt = 1;</code>
       */
      public Builder clearEmcrypt() {
        if (emcryptBuilder_ == null) {
          emcrypt_ = null;
          onChanged();
        } else {
          emcrypt_ = null;
          emcryptBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Emcrypt emcrypt = 1;</code>
       */
      public com.wolf.javabean.Key.Emcrypt.Builder getEmcryptBuilder() {
        
        onChanged();
        return getEmcryptFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.wolf.javabean.Emcrypt emcrypt = 1;</code>
       */
      public com.wolf.javabean.Key.EmcryptOrBuilder getEmcryptOrBuilder() {
        if (emcryptBuilder_ != null) {
          return emcryptBuilder_.getMessageOrBuilder();
        } else {
          return emcrypt_ == null ?
              com.wolf.javabean.Key.Emcrypt.getDefaultInstance() : emcrypt_;
        }
      }
      /**
       * <code>optional .com.wolf.javabean.Emcrypt emcrypt = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolf.javabean.Key.Emcrypt, com.wolf.javabean.Key.Emcrypt.Builder, com.wolf.javabean.Key.EmcryptOrBuilder> 
          getEmcryptFieldBuilder() {
        if (emcryptBuilder_ == null) {
          emcryptBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wolf.javabean.Key.Emcrypt, com.wolf.javabean.Key.Emcrypt.Builder, com.wolf.javabean.Key.EmcryptOrBuilder>(
                  getEmcrypt(),
                  getParentForChildren(),
                  isClean());
          emcrypt_ = null;
        }
        return emcryptBuilder_;
      }

      private com.wolf.javabean.Key.Dmcrypt dmcrypt_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolf.javabean.Key.Dmcrypt, com.wolf.javabean.Key.Dmcrypt.Builder, com.wolf.javabean.Key.DmcryptOrBuilder> dmcryptBuilder_;
      /**
       * <code>optional .com.wolf.javabean.Dmcrypt dmcrypt = 2;</code>
       */
      public boolean hasDmcrypt() {
        return dmcryptBuilder_ != null || dmcrypt_ != null;
      }
      /**
       * <code>optional .com.wolf.javabean.Dmcrypt dmcrypt = 2;</code>
       */
      public com.wolf.javabean.Key.Dmcrypt getDmcrypt() {
        if (dmcryptBuilder_ == null) {
          return dmcrypt_ == null ? com.wolf.javabean.Key.Dmcrypt.getDefaultInstance() : dmcrypt_;
        } else {
          return dmcryptBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.wolf.javabean.Dmcrypt dmcrypt = 2;</code>
       */
      public Builder setDmcrypt(com.wolf.javabean.Key.Dmcrypt value) {
        if (dmcryptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dmcrypt_ = value;
          onChanged();
        } else {
          dmcryptBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Dmcrypt dmcrypt = 2;</code>
       */
      public Builder setDmcrypt(
          com.wolf.javabean.Key.Dmcrypt.Builder builderForValue) {
        if (dmcryptBuilder_ == null) {
          dmcrypt_ = builderForValue.build();
          onChanged();
        } else {
          dmcryptBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Dmcrypt dmcrypt = 2;</code>
       */
      public Builder mergeDmcrypt(com.wolf.javabean.Key.Dmcrypt value) {
        if (dmcryptBuilder_ == null) {
          if (dmcrypt_ != null) {
            dmcrypt_ =
              com.wolf.javabean.Key.Dmcrypt.newBuilder(dmcrypt_).mergeFrom(value).buildPartial();
          } else {
            dmcrypt_ = value;
          }
          onChanged();
        } else {
          dmcryptBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Dmcrypt dmcrypt = 2;</code>
       */
      public Builder clearDmcrypt() {
        if (dmcryptBuilder_ == null) {
          dmcrypt_ = null;
          onChanged();
        } else {
          dmcrypt_ = null;
          dmcryptBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.wolf.javabean.Dmcrypt dmcrypt = 2;</code>
       */
      public com.wolf.javabean.Key.Dmcrypt.Builder getDmcryptBuilder() {
        
        onChanged();
        return getDmcryptFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.wolf.javabean.Dmcrypt dmcrypt = 2;</code>
       */
      public com.wolf.javabean.Key.DmcryptOrBuilder getDmcryptOrBuilder() {
        if (dmcryptBuilder_ != null) {
          return dmcryptBuilder_.getMessageOrBuilder();
        } else {
          return dmcrypt_ == null ?
              com.wolf.javabean.Key.Dmcrypt.getDefaultInstance() : dmcrypt_;
        }
      }
      /**
       * <code>optional .com.wolf.javabean.Dmcrypt dmcrypt = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolf.javabean.Key.Dmcrypt, com.wolf.javabean.Key.Dmcrypt.Builder, com.wolf.javabean.Key.DmcryptOrBuilder> 
          getDmcryptFieldBuilder() {
        if (dmcryptBuilder_ == null) {
          dmcryptBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wolf.javabean.Key.Dmcrypt, com.wolf.javabean.Key.Dmcrypt.Builder, com.wolf.javabean.Key.DmcryptOrBuilder>(
                  getDmcrypt(),
                  getParentForChildren(),
                  isClean());
          dmcrypt_ = null;
        }
        return dmcryptBuilder_;
      }

      private java.lang.Object type_ = "";
      /**
       * <pre>
       *2是用户密码请求加密,3是用户密码请求解密,-1是加密解密失败，1是加密解密成功
       * </pre>
       *
       * <code>optional string type = 3;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *2是用户密码请求加密,3是用户密码请求解密,-1是加密解密失败，1是加密解密成功
       * </pre>
       *
       * <code>optional string type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *2是用户密码请求加密,3是用户密码请求解密,-1是加密解密失败，1是加密解密成功
       * </pre>
       *
       * <code>optional string type = 3;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *2是用户密码请求加密,3是用户密码请求解密,-1是加密解密失败，1是加密解密成功
       * </pre>
       *
       * <code>optional string type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *2是用户密码请求加密,3是用户密码请求解密,-1是加密解密失败，1是加密解密成功
       * </pre>
       *
       * <code>optional string type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 4;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 4;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 4;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 4;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.wolf.javabean.Datas)
    }

    // @@protoc_insertion_point(class_scope:com.wolf.javabean.Datas)
    private static final com.wolf.javabean.Key.Datas DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wolf.javabean.Key.Datas();
    }

    public static com.wolf.javabean.Key.Datas getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Datas>
        PARSER = new com.google.protobuf.AbstractParser<Datas>() {
      public Datas parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Datas(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Datas> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Datas> getParserForType() {
      return PARSER;
    }

    public com.wolf.javabean.Key.Datas getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmcryptOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wolf.javabean.Emcrypt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *加密前请求
     * </pre>
     *
     * <code>optional string data = 1;</code>
     */
    java.lang.String getData();
    /**
     * <pre>
     *加密前请求
     * </pre>
     *
     * <code>optional string data = 1;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <pre>
     *加密后返回
     * </pre>
     *
     * <code>optional bytes rdata = 2;</code>
     */
    com.google.protobuf.ByteString getRdata();
  }
  /**
   * <pre>
   *加密
   * </pre>
   *
   * Protobuf type {@code com.wolf.javabean.Emcrypt}
   */
  public  static final class Emcrypt extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.wolf.javabean.Emcrypt)
      EmcryptOrBuilder {
    // Use Emcrypt.newBuilder() to construct.
    private Emcrypt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Emcrypt() {
      data_ = "";
      rdata_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Emcrypt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 18: {

              rdata_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wolf.javabean.Key.internal_static_com_wolf_javabean_Emcrypt_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wolf.javabean.Key.internal_static_com_wolf_javabean_Emcrypt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wolf.javabean.Key.Emcrypt.class, com.wolf.javabean.Key.Emcrypt.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private volatile java.lang.Object data_;
    /**
     * <pre>
     *加密前请求
     * </pre>
     *
     * <code>optional string data = 1;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *加密前请求
     * </pre>
     *
     * <code>optional string data = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString rdata_;
    /**
     * <pre>
     *加密后返回
     * </pre>
     *
     * <code>optional bytes rdata = 2;</code>
     */
    public com.google.protobuf.ByteString getRdata() {
      return rdata_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, data_);
      }
      if (!rdata_.isEmpty()) {
        output.writeBytes(2, rdata_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, data_);
      }
      if (!rdata_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, rdata_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wolf.javabean.Key.Emcrypt)) {
        return super.equals(obj);
      }
      com.wolf.javabean.Key.Emcrypt other = (com.wolf.javabean.Key.Emcrypt) obj;

      boolean result = true;
      result = result && getData()
          .equals(other.getData());
      result = result && getRdata()
          .equals(other.getRdata());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + RDATA_FIELD_NUMBER;
      hash = (53 * hash) + getRdata().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wolf.javabean.Key.Emcrypt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.Key.Emcrypt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.Key.Emcrypt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.Key.Emcrypt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.Key.Emcrypt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.Key.Emcrypt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.Key.Emcrypt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.Key.Emcrypt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.Key.Emcrypt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.Key.Emcrypt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wolf.javabean.Key.Emcrypt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *加密
     * </pre>
     *
     * Protobuf type {@code com.wolf.javabean.Emcrypt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wolf.javabean.Emcrypt)
        com.wolf.javabean.Key.EmcryptOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wolf.javabean.Key.internal_static_com_wolf_javabean_Emcrypt_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wolf.javabean.Key.internal_static_com_wolf_javabean_Emcrypt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wolf.javabean.Key.Emcrypt.class, com.wolf.javabean.Key.Emcrypt.Builder.class);
      }

      // Construct using com.wolf.javabean.Key.Emcrypt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        data_ = "";

        rdata_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wolf.javabean.Key.internal_static_com_wolf_javabean_Emcrypt_descriptor;
      }

      public com.wolf.javabean.Key.Emcrypt getDefaultInstanceForType() {
        return com.wolf.javabean.Key.Emcrypt.getDefaultInstance();
      }

      public com.wolf.javabean.Key.Emcrypt build() {
        com.wolf.javabean.Key.Emcrypt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wolf.javabean.Key.Emcrypt buildPartial() {
        com.wolf.javabean.Key.Emcrypt result = new com.wolf.javabean.Key.Emcrypt(this);
        result.data_ = data_;
        result.rdata_ = rdata_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wolf.javabean.Key.Emcrypt) {
          return mergeFrom((com.wolf.javabean.Key.Emcrypt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wolf.javabean.Key.Emcrypt other) {
        if (other == com.wolf.javabean.Key.Emcrypt.getDefaultInstance()) return this;
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (other.getRdata() != com.google.protobuf.ByteString.EMPTY) {
          setRdata(other.getRdata());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wolf.javabean.Key.Emcrypt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wolf.javabean.Key.Emcrypt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <pre>
       *加密前请求
       * </pre>
       *
       * <code>optional string data = 1;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *加密前请求
       * </pre>
       *
       * <code>optional string data = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *加密前请求
       * </pre>
       *
       * <code>optional string data = 1;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *加密前请求
       * </pre>
       *
       * <code>optional string data = 1;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *加密前请求
       * </pre>
       *
       * <code>optional string data = 1;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString rdata_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *加密后返回
       * </pre>
       *
       * <code>optional bytes rdata = 2;</code>
       */
      public com.google.protobuf.ByteString getRdata() {
        return rdata_;
      }
      /**
       * <pre>
       *加密后返回
       * </pre>
       *
       * <code>optional bytes rdata = 2;</code>
       */
      public Builder setRdata(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rdata_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *加密后返回
       * </pre>
       *
       * <code>optional bytes rdata = 2;</code>
       */
      public Builder clearRdata() {
        
        rdata_ = getDefaultInstance().getRdata();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.wolf.javabean.Emcrypt)
    }

    // @@protoc_insertion_point(class_scope:com.wolf.javabean.Emcrypt)
    private static final com.wolf.javabean.Key.Emcrypt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wolf.javabean.Key.Emcrypt();
    }

    public static com.wolf.javabean.Key.Emcrypt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Emcrypt>
        PARSER = new com.google.protobuf.AbstractParser<Emcrypt>() {
      public Emcrypt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Emcrypt(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Emcrypt> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Emcrypt> getParserForType() {
      return PARSER;
    }

    public com.wolf.javabean.Key.Emcrypt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DmcryptOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wolf.javabean.Dmcrypt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *解密前请求
     * </pre>
     *
     * <code>optional bytes data = 1;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <pre>
     *解密后返回
     * </pre>
     *
     * <code>optional string rdata = 2;</code>
     */
    java.lang.String getRdata();
    /**
     * <pre>
     *解密后返回
     * </pre>
     *
     * <code>optional string rdata = 2;</code>
     */
    com.google.protobuf.ByteString
        getRdataBytes();
  }
  /**
   * <pre>
   *解密
   * </pre>
   *
   * Protobuf type {@code com.wolf.javabean.Dmcrypt}
   */
  public  static final class Dmcrypt extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.wolf.javabean.Dmcrypt)
      DmcryptOrBuilder {
    // Use Dmcrypt.newBuilder() to construct.
    private Dmcrypt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dmcrypt() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      rdata_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Dmcrypt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              data_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              rdata_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wolf.javabean.Key.internal_static_com_wolf_javabean_Dmcrypt_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wolf.javabean.Key.internal_static_com_wolf_javabean_Dmcrypt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wolf.javabean.Key.Dmcrypt.class, com.wolf.javabean.Key.Dmcrypt.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     *解密前请求
     * </pre>
     *
     * <code>optional bytes data = 1;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int RDATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object rdata_;
    /**
     * <pre>
     *解密后返回
     * </pre>
     *
     * <code>optional string rdata = 2;</code>
     */
    public java.lang.String getRdata() {
      java.lang.Object ref = rdata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rdata_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *解密后返回
     * </pre>
     *
     * <code>optional string rdata = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRdataBytes() {
      java.lang.Object ref = rdata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rdata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
      if (!getRdataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rdata_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      if (!getRdataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, rdata_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wolf.javabean.Key.Dmcrypt)) {
        return super.equals(obj);
      }
      com.wolf.javabean.Key.Dmcrypt other = (com.wolf.javabean.Key.Dmcrypt) obj;

      boolean result = true;
      result = result && getData()
          .equals(other.getData());
      result = result && getRdata()
          .equals(other.getRdata());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + RDATA_FIELD_NUMBER;
      hash = (53 * hash) + getRdata().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wolf.javabean.Key.Dmcrypt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.Key.Dmcrypt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.Key.Dmcrypt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolf.javabean.Key.Dmcrypt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolf.javabean.Key.Dmcrypt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.Key.Dmcrypt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.Key.Dmcrypt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.Key.Dmcrypt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolf.javabean.Key.Dmcrypt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolf.javabean.Key.Dmcrypt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wolf.javabean.Key.Dmcrypt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *解密
     * </pre>
     *
     * Protobuf type {@code com.wolf.javabean.Dmcrypt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wolf.javabean.Dmcrypt)
        com.wolf.javabean.Key.DmcryptOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wolf.javabean.Key.internal_static_com_wolf_javabean_Dmcrypt_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wolf.javabean.Key.internal_static_com_wolf_javabean_Dmcrypt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wolf.javabean.Key.Dmcrypt.class, com.wolf.javabean.Key.Dmcrypt.Builder.class);
      }

      // Construct using com.wolf.javabean.Key.Dmcrypt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;

        rdata_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wolf.javabean.Key.internal_static_com_wolf_javabean_Dmcrypt_descriptor;
      }

      public com.wolf.javabean.Key.Dmcrypt getDefaultInstanceForType() {
        return com.wolf.javabean.Key.Dmcrypt.getDefaultInstance();
      }

      public com.wolf.javabean.Key.Dmcrypt build() {
        com.wolf.javabean.Key.Dmcrypt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wolf.javabean.Key.Dmcrypt buildPartial() {
        com.wolf.javabean.Key.Dmcrypt result = new com.wolf.javabean.Key.Dmcrypt(this);
        result.data_ = data_;
        result.rdata_ = rdata_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wolf.javabean.Key.Dmcrypt) {
          return mergeFrom((com.wolf.javabean.Key.Dmcrypt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wolf.javabean.Key.Dmcrypt other) {
        if (other == com.wolf.javabean.Key.Dmcrypt.getDefaultInstance()) return this;
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (!other.getRdata().isEmpty()) {
          rdata_ = other.rdata_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wolf.javabean.Key.Dmcrypt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wolf.javabean.Key.Dmcrypt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *解密前请求
       * </pre>
       *
       * <code>optional bytes data = 1;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       *解密前请求
       * </pre>
       *
       * <code>optional bytes data = 1;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *解密前请求
       * </pre>
       *
       * <code>optional bytes data = 1;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private java.lang.Object rdata_ = "";
      /**
       * <pre>
       *解密后返回
       * </pre>
       *
       * <code>optional string rdata = 2;</code>
       */
      public java.lang.String getRdata() {
        java.lang.Object ref = rdata_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rdata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *解密后返回
       * </pre>
       *
       * <code>optional string rdata = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRdataBytes() {
        java.lang.Object ref = rdata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rdata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *解密后返回
       * </pre>
       *
       * <code>optional string rdata = 2;</code>
       */
      public Builder setRdata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rdata_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *解密后返回
       * </pre>
       *
       * <code>optional string rdata = 2;</code>
       */
      public Builder clearRdata() {
        
        rdata_ = getDefaultInstance().getRdata();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *解密后返回
       * </pre>
       *
       * <code>optional string rdata = 2;</code>
       */
      public Builder setRdataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rdata_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.wolf.javabean.Dmcrypt)
    }

    // @@protoc_insertion_point(class_scope:com.wolf.javabean.Dmcrypt)
    private static final com.wolf.javabean.Key.Dmcrypt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wolf.javabean.Key.Dmcrypt();
    }

    public static com.wolf.javabean.Key.Dmcrypt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Dmcrypt>
        PARSER = new com.google.protobuf.AbstractParser<Dmcrypt>() {
      public Dmcrypt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Dmcrypt(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dmcrypt> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dmcrypt> getParserForType() {
      return PARSER;
    }

    public com.wolf.javabean.Key.Dmcrypt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wolf_javabean_Datas_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wolf_javabean_Datas_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wolf_javabean_Emcrypt_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wolf_javabean_Emcrypt_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wolf_javabean_Dmcrypt_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wolf_javabean_Dmcrypt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tKey.proto\022\021com.wolf.javabean\"{\n\005Datas\022" +
      "+\n\007emcrypt\030\001 \001(\0132\032.com.wolf.javabean.Emc" +
      "rypt\022+\n\007dmcrypt\030\002 \001(\0132\032.com.wolf.javabea" +
      "n.Dmcrypt\022\014\n\004type\030\003 \001(\t\022\n\n\002id\030\004 \001(\t\"&\n\007E" +
      "mcrypt\022\014\n\004data\030\001 \001(\t\022\r\n\005rdata\030\002 \001(\014\"&\n\007D" +
      "mcrypt\022\014\n\004data\030\001 \001(\014\022\r\n\005rdata\030\002 \001(\tb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_wolf_javabean_Datas_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wolf_javabean_Datas_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wolf_javabean_Datas_descriptor,
        new java.lang.String[] { "Emcrypt", "Dmcrypt", "Type", "Id", });
    internal_static_com_wolf_javabean_Emcrypt_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_wolf_javabean_Emcrypt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wolf_javabean_Emcrypt_descriptor,
        new java.lang.String[] { "Data", "Rdata", });
    internal_static_com_wolf_javabean_Dmcrypt_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_wolf_javabean_Dmcrypt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wolf_javabean_Dmcrypt_descriptor,
        new java.lang.String[] { "Data", "Rdata", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
